<h3>Life’s Blend <br><small>By: Nicole Marie G. Dumayac</small>   </h3>                                                     



<h4></h4>

   <p>The smooth aroma of the warm drink made Kelly feel better. She took a sip of her medium cupped Americano and it was a bitter-sweet nostalgic experience. She can still remember the last time she had coffee; it was when the only man that she loved was still alive. He was her caffeine partner, he made her mornings bright even for a rainy day. Kelly glanced outside the coffee shop; people were busy and getting along with their own lives while here she was still mourning from being left behind. A tear ran down to her cheeks, she wiped it off with her palm and took one last slurp of her coffee. She got up and ordered an espresso in a cup. “Trying to stay awake in this hectic day huh?” The barista jokingly asked. “What?” She replied confused. “This count as your second coffee for this hour.” Kelly forced a smile to what the barista has said. “It’s for someone else but actually, make my order a double.” The barista made another espresso, a few minutes later it was finished. He handed it to Kelly and told her to enjoy her drink. Kelly stepped outside the coffee shop and called out for a cab and got inside. “Shady Cove, New Haven Lilac Road.” The driver then started the cab. Kelly embraced the cup with her hands, she felt the warmth of the drink; she hoped it would stay warm until she reach the town. Kelly observed the city, stores were having Prom sales. She thought about him again, memories of him were still fresh; one dreamy night that turned into a tragic incident.</p>
   
   
  <p> Kelly made her way throughout the crowd of students. She took a deep breath when she made it out from the school’s main hallway. A man standing outside a black mustang waved at her with a smile, she ran towards him and gave him a tight hug. Kelly grinned and pointed out the big banner hanging outside the school’s building. “What’s with that?” He asked. Kelly sighed and walked to the other side of the vehicle. “Hey, what did I do?” Kelly ignored his question and got inside the car. He got inside the car and looked at her with a goofy face. “Quit acting funny, Dad.” She said. “Calm down I was just playing around with you. Where can we buy you a dress?”  Asked her father out of the blue, her jaw dropped and felt her heart skipped a beat. The two spent the rest of the day shopping from store to store, and later on found themselves in their favorite coffee shop. “An espresso for you and a cappuccino for me.” Kelly exclaimed. They enjoyed each other’s company, Kelly was contented even if she didn’t have a mother, boyfriend and a best friend because for Kelly her Dad was all of them. “Just promise me there won’t be hanging out with duded.” Her father said. “And promise me you’ll drive me to prom.” She replied.</p>
   
   
  <p> Friday came; Kelly was already home ready for the night. She was patiently waiting for her father to come home from work and drive her to prom. As she was waiting, her father was on his way home driving his car; he couldn’t let Kelly wait. He made a promise. He locked his eyes on the road, there was a blind curve ahead, as he made a slow turn a raging van came in sight. He steered his wheel and tried to avoid the van but fate happened. The car bumped into a large tree, his head was hit on the steering wheel and broken glasses were buried in his skin. He couldn’t move and was losing great amount of blood. Minutes later he heard sirens, he was pulled out of the damaged car and was carried in a stretcher. All he could think about was his daughter. “Kelly…” He spoke weakly. “Stay with us sir, you’ll be alright.” A rescuer said. “I need..to take..Kelly..to prom.” He used all his remaining strength. Those were the last words that came out from his mouth before his life was taken.</p>
  
   <p>Kelly blinked and took a deep breathe; more tears came out from her eyes. The night that should’ve been the night of her life turned into horrifying memory. “Ma’am? We’re here.” The cab driver said with a concerned tone. Kelly gave him the money and immediately got out of the cab. She went to her father’s grave and placed one cup of espresso. “Flowers are too common. You’re probably laughing at my stupidity right now of bringing you coffee as if you’re going to rise up from the grave and drink it. But please no, that’d be really creepy.” Kelly laughed. She missed her father and those times that they would throw jokes to each other but now it’s like she’s talking to air. Kelly left the place and decided to take a walk in her hometown. She passed by the local coffee shop that she and her father always spend time in. Kelly thought of having her third cup of coffee for the day, she entered the coffee shop and was greeted by the barista that she knew. “Kelly! How are you?” The lady said. “I’m fine, glad we met again.” Kelly replied with a smile. “You’ve never stop with this caffeine addiction. What can I offer you today? You’re favorite Cappuccino?” She asked. “I’ll go with caramel frappe this time.” Kelly said. She took the frappe and saw the table that she and her father used to sit, that was there spot. She sat down, placed her frappe and stared at the words written on the table; she took a sip of the frappe and noticed the carving on the table. It was her father’s; she remembered the time he carved it. Five years ago when she had her very first cup of coffee. “Life is good and that’s the way it should be.” She whispered the words carved by his father. Kelly chuckled when she remembered why her father carved it, he lack out of ink so he struggled carving with the pen’s point. 
   Kelly looked on the bright side, it was a bitter happening but her father brewed her to be thankful and be optimistic always. If it wasn’t for her father’s demise, her mother wouldn’t have showed up and Kelly wouldn’t have learned to go out from her shell and talk to people like she never did in her High school.  The night of her accident might be unsweetened but their bond and her love for her father was as strong as an espresso and sweet like a frappe. –END.</p>
